### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by phuongphally** [akhuntsaria/spring-boot-api-gateway#1]
`POST` to `http://localhost:8080/auth/v1/login` 

and use 

```JSON
{
  "username": "username",
  "password": "password"
}
 ```

response status 200 with empty body but there is no jwt token found in response

**Comment by akagi1** [comment]
JWT is returned in response header "Authorization".
![header](https://user-images.githubusercontent.com/49805336/110173341-dfdbbe80-7e17-11eb-9073-4b06284f0fe4.PNG)
